### ISSUE TITLE
カスタム属性を登録できるようにしてほしい（要望）

### ISSUE THREAD

**Issue by imatakutin** [nulab/backlog-bulk-issue-registration-gas#2]
Backlogでカスタム属性を使った場合に利用の幅が大きく広がります。
カスタム属性を一括で登録できるようにしたい。

**Comment by ikikko** [comment]
カスタム属性の実装はちょっと考えないといけないことが多いのですよね。
プロジェクト・種別によって必須項目などが入ってきてしまうので。

私の方で一から実装するのは時間がとれなさそうなのですが、
プルリクエストベースでやり取りできるようでしたら、検討したいと思います。

**Comment by shomatan** [comment]
imatakutin さん
いつもBacklogをご利用いただきありがとうございます。
本日、カスタム属性対応のリリースを行いました。
いくつか制限事項がございますので、詳細はREADMEをご参照ください。
今後ともよろしくお願いいたします。
