### ISSUE TITLE
【質問】データを取得できません

### ISSUE THREAD

**Issue by maokura** [nulab/backlog-bulk-issue-registration-gas#27]
「STEP1: Backlogからデータを取得する」を実行しても、表中のデータが変わりません。

**Comment by maokura** [comment]
手順ミスだったようです。申し訳ありません。
しかし、データをアップロードしたところ、添付の画像のように（文字を潰しています）
同じ課題キーが2つ表示されるという現象が発生しています。

![screenclip](https://user-images.githubusercontent.com/6056099/48595162-df912e00-e996-11e8-9e76-a19f9af5606e.jpg)

**Comment by shomatan** [comment]
親子課題がすべて表示されているので重複して表示されているかと思います。
以下の画像のように`子課題以外`を指定していただけますでしょうか。
![image](https://user-images.githubusercontent.com/17427345/48595612-cf7a4e00-e998-11e8-8a0c-c83104c0f6e8.png)

**Comment by shomatan** [comment]
それではCloseさせていただきます。
今後ともBacklogをよろしくお願いいたします。
