### ISSUE TITLE
取込・登録共にエラーになります

### ISSUE THREAD

**Issue by ipros-asahina** [nulab/backlog-bulk-issue-registration-gas#28]
STEP1,2共に「UiApp has been deprecated. Please use HtmlService instead」というエラーが発生します。
先週ぐらいまでは使えていたと思うのですが。

バージョンは 2.0.4 です。

![2019-01-28_17h13_59](https://user-images.githubusercontent.com/12856459/51822793-ae32c800-2320-11e9-812d-f1d0a706cbc2.png)

**Comment by shomatan** [comment]
@ipros-asahina 様
いつもBacklogをご利用いただきありがとうございます。
エラーの件でご不便おかけしております。

ご報告いただいておりますエラーは現在対応中でございます。
近日中にリリースする予定ですので、いましばらくお待ちいただけますでしょうか。
よろしくお願いいたします。
