### ISSUE TITLE
一括登録したタスクのスケジュールが一日前にずれる

### ISSUE THREAD

**Issue by bp-takahashi** [nulab/backlog-bulk-issue-registration-gas#29]
新規プロジェクトや定期的に繰り返す作業の登録の際に便利に使わせていただいております。

2.0.4のバージョンでエラーが発生し、登録が行えなくなったので、2.1.0のバージョンへ移行したところ、開始日/終了日の日程が一日前にずれて作成されるようになりました。

お手数をおかけいたしますが、ご確認いただけますでしょうか。

**Comment by shomatan** [comment]
@bp-takahashi さま

いつもBacklogをご利用いただきありがとうございます！

日付が1日ずれるということで大変ご不便おかけしております🙏
この問題は2.1.0リリース直後に修正しましたが解消していない可能性があります。
恐れ入りますが、いつごろ作成されたか教えていただけますでしょうか。

よろしくお願いいたします🙇‍♂️

**Comment by bp-takahashi** [comment]
早速ご回答いただきありがとうございました。

02/22 11:12に取得したシートを利用させていただいておりました。

引き続きご確認の程よろしくお願いいたします。

**Comment by shomatan** [comment]
@bp-takahashi さま

こちらこそありがとうございます！
確かに2/22に同様の問い合わせを受けておりました。

大変恐縮なのですが以下の方法をご検討いただけないでしょうか。
1. 再度スプレッドシートをコピーする(現在解消しております)
2. 現在ご利用中のスプレッドシートのタイムゾーンを変更する

2の場合の変更方法をご案内いたします。

1. スプレッドシートを開く
2. メニューの[ツール] > [スクリプトエディタ]を開く (新しいタブで開かれる)
3. メニューの[ファイル] > [プロジェクトプロパティ]を開く
4. 下にスクロールするとタイムゾーンがあるので、[(GMT+09:00)Tokyo]に設定する
5. 保存して完了（スクリプトエディタは閉じてOKです）

お手数おかけしますがよろしくお願いいたします🙇‍♂️

**Comment by bp-takahashi** [comment]
ありがとうございます！
ご教授いただいた手順で指定の日付にタスクを作成することができました。

今後ともよろしくお願いいたします。
