### ISSUE TITLE
一括登録が失敗している

### ISSUE THREAD

**Issue by maisang2** [nulab/backlog-bulk-issue-registration-gas#31]
TypeError: Cannot find function split in object Fri Mar 29 2019 00:00:00 GMT+0900 (JST). at [unknown function](bundle:822) at [unknown function](bundle:844) at [unknown function](bundle:371) at [unknown function](bundle:486) at [unknown function](bundle:486) at [unknown function](bundle:1104)

**Comment by shomatan** [comment]
@maisang2 様

いつもBacklogをご利用いただきありがとうございます。

入力された内容についてお伺いしたいので、お手数ですが下記の問い合わせフォームからご連絡いただけないでしょうか。
https://backlog.com/ja/contact/

よろしくお願いいたします。
