### ISSUE TITLE
2020-04-21最新のスプレッドシート中の「step1」で「Unexpected token < in JSON...」と表示

### ISSUE THREAD

**Issue by yuta-hidaka** [nulab/backlog-bulk-issue-registration-gas#41]
掲題の通りです。

前に実行した際(2-3か月前)にはエラーにならなかったのですが、最新版だとエラーになります。

2-3か月前に使用したスプレッドシートと、最新版のスプレッドシート両方で同じエラーが出ます。

![image](https://user-images.githubusercontent.com/46583585/79957081-091f8480-84bc-11ea-9677-7b743e6eafc6.png)

**Comment by shomatan** [comment]
@yuta-hidaka 様
いつもBacklogをご利用いただきありがとうございます！
表示のエラーの件でご不便おかけしております。

お使いのBacklogにアクセス制限の設定をされていませんでしょうか。
ご確認のほど、よろしくお願いいたします。

**Comment by yuta-hidaka** [comment]
@shomatan 様
ありがとうございます！

担当者に確認したところ、アクセス制限がかかっているとのことでした。
こちらを解除するには、現行、弊社で加入している「スタータークラシック」から「スタンダードクラシック」に変更しなければならないとも担当者より報告をもらいました。

こちらプランの変更をしなければアクセス制限が解除できないのでしょうか。

前まで同じプランで全く問題なく使えていたので、こちらについてご助言いただけましたら幸いです。

よろしくお願い申し上げます。

**Comment by shomatan** [comment]
@yuta-hidaka 様
お調べいただきありがとうございます。

スタータープランであればIPアドレスによるアクセス制限機能はご利用いただけないのですが、
詳細をお伺いしたいので https://backlog.com/ja/contact/ よりお問い合わせいただけないでしょうか。
お手数おかけしますがよろしくお願いいたします🙏

**Comment by shomatan** [comment]
こちらは一旦クローズさせていただきます
