### ISSUE TITLE
【質問】認証が通りません。

### ISSUE THREAD

**Issue by naoki-sakamoto** [nulab/backlog-bulk-issue-registration-gas#6]
こちらに投稿しても良いものか迷いましたが質問させてください。
課題一括登録ボタンを押下した後の認証画面でエラーメッセージ「このアプリは承認されていません」と出てしまいます。（キャプチャを添付）

解決方法を教えてください。

![2017-11-08 18 22 10](https://user-images.githubusercontent.com/1646565/32541036-d0c018ec-c4b1-11e7-9f53-829546c95645.png)

Googleによる確認が必要と書かれていますがその予定はありますか？

**Comment by ikikko** [comment]
返事遅くなってすいません。

左下の「詳細」をクリックしてみて、承認的なプロセスが進められないでしょうか？

**Comment by shomatan** [comment]
@naoki-sakamoto 様
その後いかがでしょうか？
このIssueは一旦Closeさせていただきますね。
