### ISSUE TITLE
str.split is not a function error

### ISSUE THREAD

**Issue by bacnp1** [nulab/backlog-bulk-issue-registration-gas#68]
I have been using this for a few months now and have set up everything as described in https://github.com/nulab/backlog-bulk-issue-registration-gas/blob/master/README_en.md

Suddenly now i get this error when attempting to register the issue to backlog
Can anyone help me with this 
<img width="332" alt="Screenshot 2023-10-02 182437" src="https://github.com/nulab/backlog-bulk-issue-registration-gas/assets/108322501/7f8d286b-9561-44ef-bf62-6513a6ce9133">

日本語
数ヶ月間で、これを問題なく利用できましたが、突然今日このエラーが発生しました。

誰かが助けていただけないでしょうか。

**Comment by jtakakura** [comment]
@bacnp1 Thank you for using our Backlog service.
If you have any questions about our services, please click on the following link, then complete and submit the contact form.

https://nulab.com/contact/
